/* @formatter:off * * © David M Rosenberg * * Topic: Stacks and Recursion *  * Usage restrictions: *  * You may use this code for exploration, experimentation, and furthering your * learning for this course. You may not use this code for any other * assignments, in my course or elsewhere, without explicit permission, in * advance, from myself (and the instructor of any other course). *  * Further, you may not post (including in a public repository such as on github) * nor otherwise share this code with anyone other than current students in my  * sections of this course. *  * Violation of these usage restrictions will be considered a violation of * Wentworth Institute of Technology's Academic Honesty Policy.  Unauthorized posting * or use of this code may also be considered copyright infringement and may subject * the poster and/or the owners/operators of said websites to legal and/or financial * penalties.  Students are permitted to store this code in a private repository * or other private cloud-based storage. * * Do not modify or remove this notice. * * @formatter:on */package edu.wit.scds.ds.stacks ;import java.util.EmptyStackException ;/** * An interface for the ADT stack. * * @author Frank M. Carrano * @author Timothy M. Henry * * @version 5.0 * * @author Dave Rosenberg
 *
 * @version 5.1 2022-10-16 Adapted for class use
 * @version 5.2 2024-02-22 reorder methods
 *
 * @param <T> *     the class of item to be stored on the stack
 */public interface StackInterface<T>    {    /**
     * Removes all entries from this stack.
     */
    public void clear() ;    /**     * Detects whether this stack is empty.     *     * @return true if the stack is empty.
     */    public boolean isEmpty() ;    /**     * Retrieves this stack's top entry.     *     * @return The object at the top of the stack.     *     * @throws EmptyStackException     *     if the stack is empty before the operation.     */    public T peek() ;    /**     * Removes and returns this stack's top entry.     *     * @return The object at the top of the stack.     *     * @throws EmptyStackException     *     if the stack is empty before the operation.     */    public T pop() ;    /**     * Adds a new entry to the top of this stack.     *     * @param newEntry     *     An object to be added to the stack.     */    public void push( T newEntry ) ;    }   // end interface StackInterface